const wordsList = {
  estados: [
    "Acre",
    "Alagoas",
    "Amapá",
    "Amazonas",
    "Bahia",
    "Ceará",
    "Distrito Federal",
    "Espírito Santo",
    "Goiás",
    "Maranhão",
    "Mato Grosso",
    "Mato Grosso do Sul",
    "Minas Gerais",
    "Pará",
    "Paraíba",
    "Paraná",
    "Pernambuco",
    "Piauí",
    "Rio de Janeiro",
    "Rio Grande do Norte",
    "Rio Grande do Sul",
    "Rondônia",
    "Roraima",
    "Santa Catarina",
    "São Paulo",
    "Sergipe",
    "Tocantins",
  ],
  fruta: [
    "Banana",
    "Maçã",
    "Pêra",
    "Mamão",
    "Laranja",
    "Morango",
    "Uva",
    "Pêssego",
    "Amora",
    "Ameixa",
    "Abacaxi",
    "Melancia",
    "Caju",
    "Manga",
    "Kiwi",
  ],
  corpo: [
    "Braço",
    "Perna",
    "Cérebro",
    "Pescoço",
    "Olhos",
    "Mão",
    "Cabelo",
    "Dedos",
    "Orelhas",
    "Joelho",
    "Cotovelo",
    "Fígado",
    "Estômago",
    "Coração",
  ],
  computador: [
    "Mouse",
    "Teclado",
    "Monitor",
    "Gabinete",
    "Carregador",
    "Webcam",
    "Mousepad",
    "Placa Mãe",
    "Memória RAM",
    "Processador",
    "Notebook",
    "Headset",
  ],
  programação: [
    "Linguagem",
    "Framework",
    "JavaScript",
    "React",
    "Python",
    "Variável",
    "Função",
    "Algoritmo",
    "Frontend",
    "Backend",
    "Loop",
    "Banco de Dados",
  ],
  comida: [
    "Bolo",
    "Pizza",
    "Batata",
    "Lasanha",
    "Sorvete",
    "Macarrão",
    "Feijoada",
    "Hamburguer",
    "Chocolate",
    "Pastel",
    "Cachorro Quente",
  ],

  animais: [
    "Elefante",
    "Girafa",
    "Macaco",
    "Leão",
    "Tigre",
    "Cachorro",
    "Gato",
    "Golfinho",
    "Pinguim",
    "Rinoceronte",
    "Hipopótamo",
    "Jacaré",
    "Serpente",
  ],
  países: [
    "Brasil",
    "Argentina",
    "Canadá",
    "Japão",
    "Austrália",
    "França",
    "Itália",
    "Portugal",
    "Alemanha",
    "Rússia",
    "México",
    "Egito",
    "China",
    "Índia",
  ],
  profissões: [
    "Engenheiro",
    "Médico",
    "Professor",
    "Advogado",
    "Padeiro",
    "Eletricista",
    "Desenvolvedor",
    "Arquiteto",
    "Cozinheiro",
    "Jornalista",
    "Psicólogo",
    "Bombeiro",
    "Policial",
  ],
  instrumentos: [
    "Violão",
    "Piano",
    "Bateria",
    "Flauta",
    "Trompete",
    "Saxofone",
    "Violino",
    "Guitarra",
    "Harpa",
    "Gaita",
    "Ukulele",
  ],
};

const stages = [
  { id: 1, name: "start" },
  { id: 2, name: "game" },
  { id: 3, name: "end" },
];

//Criação de um type alias com os tipos das keys da wordsList
type wordsListKeys = keyof typeof wordsList;

//Tipo para as ForwardedRefs e para as refs do componente app
interface focusRef {
  focus: () => void;
}

export { wordsList, stages };
export type { wordsListKeys };
export type { focusRef };
